version: "3.9"

services:
    db:
        image: postgres
        hostname: postgresql
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_db:/var/lib/postgresql/data
        env_file:
            - django_ex/.env
        networks:
            - djangoEx_net

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        depends_on:
            - db
        ports:
            - "5050:80"
        env_file:
            - django_ex/.env
        restart: always
        networks:
            - djangoEx_net

    reload:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        restart: always
        env_file:
            - django_ex/.env
        command: python django_ex/manage.py livereload --host=0.0.0.0 --port=35729
        ports:
            - "35729:35729"
        volumes:
            - .:/app
        depends_on:
            - db
        networks:
            - djangoEx_net

    web:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        restart: always
        env_file:
            - django_ex/.env
        command: bash -c "python django_ex/manage.py migrate && python django_ex/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - reload
        networks:
            - djangoEx_net

volumes:
    postgres_db:


networks:
    djangoEx_net:


